# `pandas` - Indexing

In [2]:
import pandas  as pd
import numpy   as np
import sklearn as sk
(pd.__version__,
 np.__version__,
 sk.__version__
)

In [3]:
df = pd.DataFrame({'a': np.random.randn(6).astype('f4'),
                   'b': [True, False] * 3,
                   'c': [1.0, 2.0] * 3})
df
df.select_dtypes(include='bool')

In [4]:
%sh 
echo 'import pandas as pd' > /tmp/sdf.py
echo 'print pd.__version__' >> /tmp/sdf.py
echo 'from pandas import select_dtypes' >> /tmp/sdf.py
echo 'df = pd.DataFrame({'a': np.random.randn(6).astype('f4'),'b': [True, False] * 3,'c': [1.0, 2.0] * 3})' >> /tmp/sdf.py
echo 'df' >> /tmp/sdf.py
echo 'df.select_dtypes(include='bool')' >> /tmp/sdf.py
python /tmp/sdf.py

In [5]:
%sh pip install --upgrade pandas

In [6]:
pd.select_dtypes

In [7]:
%sh ls /dbfs/mnt/datalab-datasets/file-samples/import*

In [8]:
%sh cat /dbfs/mnt/datalab-datasets/file-samples/imports-85.names

In [9]:
column_names = ['symboling', 'normalized-losses', 'make', 'fuel-type',
                'aspiration', 'num-of-doors', 'body-style', 'drive-wheels',
                'engine-location', 'wheel-base', 'length', 'width',
                'height', 'curb-weight', 'engine-type', 'num-of-cylinders',
                'engine-size', 'fuel-system', 'bore', 'stroke',
                'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
                'highway-mpg', 'price']

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html

In [11]:
import_df = pd.read_csv('/dbfs/mnt/datalab-datasets/file-samples/imports-85.csv',
                        names=column_names,
                        dtype={'normalized-losses':'float32'}, # not necessary, demo only
                        na_values=['?'] # fixes
                       )
import_df.head() # normalized-losses should be numeric

## Dataframe Indexing

In [13]:
import_df.make[:10], type(import_df)

In [14]:
import_df[import_df.make=='audi']

In [15]:
x = import_df[import_df.make=='audi'].loc[:,'normalized-losses']
x, type(x)

In [16]:
x = import_df[import_df.make=='audi'].loc[:,['normalized-losses']]
x, type(x)

- https://pandas.pydata.org/pandas-docs/stable/missing_data.html

- http://pandas.pydata.org/pandas-docs/version/0.18/

In [19]:
import_df['normalized-losses'].isnull().sum()

In [20]:
np.where(import_df['normalized-losses'].isnull())

In [21]:
np.where(import_df['num-of-doors'].isnull())

In [22]:
import_df.apply(lambda(x): x.isnull().sum(), 
                axis=0)

__The End__